name: "Game 02"
description: "Embark on a thrilling journey through mystical lands, facing formidable foes and uncovering ancient secrets!"
tags:
  - "RPG Maker"
  - "FSK 18"
title_image: "demo-image-002.png"