services:
  game-grid:
    container_name: gamegrid
    image: pixelwelt/gamegrid:latest
    ports:
      - "8000:8000"
    volumes:
      - ./games:/static/games
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
    depends_on:
      - game-grid
    restart: always