services:
  game-grid:
    container_name: game-grid
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./games:/static/games
    restart: always