name: "Game 01"
description: "A mysterious dungeon has appeared in the heart of the kingdom. Brave adventurers are needed to explore its depths and uncover its secrets! Will you be the one to solve the mystery? Or will you fall victim to the dungeon's traps and monsters? The choice is yours! Embark on a thrilling journey through mystical lands, facing formidable foes and uncovering ancient secrets! Will you be the one to solve the mystery? "
tags:
  - "RPG Maker"
  - "Dungeon Crawler"
  - "Fantasy"
  - "Singleplayer"
  - "???"
title_image: "demo-image-001.png"