name: buildAndPushContainerToGHCR.yaml

on:
  release:
    types: [ published ]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release tag
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: PixelWelt
          repo: GameGrid

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Docker image'
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 . --tag ghcr.io/pixelwelt/gamegrid:latest --tag ghcr.io/pixelwelt/gamegrid:${{ steps.get_latest_release.outputs.release }} --push


